spring.application.name=crud
#server.port=8080
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PWD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true